### PR TITLE
Added Weather API Route

### PR DESCRIPTION
**Pull request by icepaq**
Masks our API key to the public and this simplifies the amount of information when working on the front end.

### CODE REVIEW

**Comment by RyanHaraki** [comment]
In Javascript best practice is considered to replace the keyword `var` with `let`, it's an ES6 thing and generally is better to do. Also, I think the reason that the `r` returns nothing is because you set `results = r` but never set anything equal to `results`, so naturally it's just null. Also, in the openweather.js file since there's a parameter of `city` being passed in maybe we should replace Toronto with that in the API call, but if you have it there for testing then forget what I just said. Other than that PR looks good.

**Comment by RyanHaraki** [comment]
Just thought that might be useful to consider before we merge

**Review by RyanHaraki — COMMENTED** [review]
Sorry I didn't realize I could just review here, this is the first time I've reviewed a PR LOL. Just gonna copy paste my comments.

In Javascript best practice is considered to replace the keyword `var` with `let`, it's an ES6 thing and generally is better to do. Also, I think the reason that the `r` returns nothing is because you set `results = r` but never set anything equal to `results`, so naturally it's just `null`. Also, in the openweather.js file since there's a parameter of city being passed in maybe we should replace "Toronto" with that in the API call, but if you have it there for testing then forget what I just said. Other than that PR looks good.

Just thought that might be useful to consider before we merge

**Comment by icepaq** [comment]
> In Javascript best practice is considered to replace the keyword `var` with `let`, it's an ES6 thing and generally is better to do. Also, I think the reason that the `r` returns nothing is because you set `results = r` but never set anything equal to `results`, so naturally it's just null. Also, in the openweather.js file since there's a parameter of `city` being passed in maybe we should replace Toronto with that in the API call, but if you have it there for testing then forget what I just said. Other than that PR looks good.

Just replaced var with let



The issue with results = r was I was returning results inside of a then() function. This is not allowed in JS. I'm going to have to do some more reading about this.

I'm not exactly sure what code you were looking at because the "Toronto" parameter was already gone. It's possible because my commits were all over the place that you may have read a wrong commit. To view the entire updated code you need to go into the branch I created (since I cannot fork my own repo). That will show you the updated code instead of having to look through each commit in this branch. Might make things easier in the future.

**Pull request merged**
